version: '3.8'

services:
  panel:
    build:
      context: ./react-producao
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
    ports:
      - "5556:5556"
    restart: always

  api_producao:
    build:
      context: ./api_producao
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SQLITE_URL=${SQLITE_URL}
    volumes:
      - sqlite_data:/data  
    restart: always


volumes:
  sqlite_data:
