version: '3.3'

services:
  panel:
    build:
      context: ./react-producao
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
    ports:
      - "5555:5555"
    restart: always

  api_producao:
    build:
      context: ./api_producao
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    