FROM node:alpine as build

WORKDIR /usr/app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY prisma ./prisma/


RUN npm install 
#RUN npm run prisma:generate

COPY . .


RUN npm run build

# Etapa 2: Runtime
FROM node:18-alpine

WORKDIR /usr/app
RUN apk add --no-cache openssl

# Copia arquivos do build
COPY --from=build /usr/app/node_modules ./node_modules
COPY --from=build /usr/app/package*.json ./
COPY --from=build /usr/app/dist ./dist
COPY --from=build /usr/app/prisma ./prisma

# Configura variáveis de ambiente
ENV NODE_ENV=production


# Expõe a porta
EXPOSE 3333 

# Comando de inicialização
#CMD [ "npm", "run", "start:prod" ]
CMD ["sh", "-c", "npx prisma migrate deploy --schema=prisma/sqlite.schema.prisma && npm run start:prod"]
